<?php
/**
 * @file
 * Code for the Project Open Data View feature.
 */

include_once 'opendata_view.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function opendata_view_form_opendata_settings_alter(&$form, &$formstate, $formid) {
  $form["opendata"]["opendata_path_html"] = array(
    "#type" => 'textfield',
    "#title" => t('Path to the human-readable view'),
    "#default_value" => variable_get("opendata_path_html", "data")
  );
  $form["opendata"]["opendata_path_json"] = array(
    "#type" => 'textfield',
    "#title" => t('Path to the JSON view'),
    "#default_value" => variable_get("opendata_path_json", "data.json")
  );
}
