<?php
/**
 * @file
 * Code for the Project Open Data View feature.
 */

include_once 'opendata_view.features.inc';

/**
 * Implements hook_views_post_render().
 */
function opendata_views_post_render(&$view, &$output, &$cache) {
  if ($view->name == 'opendata' && $view->current_display == 'page' && variable_get('opendata_theming', TRUE)) {
    drupal_add_css(drupal_get_path('module', 'opendata') . '/opendata.css');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function opendata_view_form_opendata_settings_alter(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'opendata_view');

  $form['opendata']['opendata_theming'] = array(
    '#type' => 'checkbox',
    '#title' => t('Apply default theming to /data page'),
    '#default_value' => variable_get('opendata_theming', TRUE),
  );
}


/**
 * Implements hook_preprocess_views_view_field().
 */
function opendata_view_preprocess_views_view_field(&$vars) {
  $url_fields = array(
    'field_opendata_data_dictionary',
    'field_opendata_conforms_to',
    'field_opendata_landing_page',
    'field_opendata_ispartof',
    'field_opendata_system_of_records',
    'field_opendata_references',
    'field_opendata_license',
    'field_opendata_identifier',
  );
  // Check to see if this is a possible url field.
  if ((!empty($vars['field']->field)) && (in_array($vars['field']->field, $url_fields))) {
    // Check to see the value is a valid url.
    if (valid_url($vars['output'], TRUE)) {
      // It is valid, run it through the l to get a link.
      $vars['output'] = l($vars['output'], $vars['output']);
    }
  }
}
