<?php
/**
 * @file opendata.module
 */

/**
 * Implements hook_menu().
 */
function opendata_menu() {
  $items['admin/config/services/opendata'] = array(
    'title' => 'OpenData',
    'description' => 'Access OpenData settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('opendata_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'opendata.admin.inc',
  );
  $items['data.json'] = array(
    'page callback' => 'opendata_data_json',
    'access arguments' => array('access content'),
    'file' => 'opendata.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function opendata_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'opendata_dataset_node_form' ) {
    if (empty($form['field_opendata_identifier'][LANGUAGE_NONE][0]['value']['#default_value'])) {
      // Code blatantly stolen from Com::generate.
      $form['field_opendata_identifier']['und'][0]['value']['#default_value'] = opendata_uuid();
    }
  }
}

/**
 * Generates a unique ID.
 *
 * @return strip
 *   A unique string.
 */
function opendata_uuid() {
  return strtolower(sprintf('%04X%04X-%04X-%04X-%04X-%04X%04X%04X', mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(16384, 20479), mt_rand(32768, 49151), mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(0, 65535)));
}

/**
 * Implements hook_views_post_render().
 */
function opendata_views_post_render(&$view, &$output, &$cache) {
  if ($view->name == 'opendata' && $view->current_display == 'page' && variable_get('opendata_theming', TRUE)) {
      drupal_add_css(drupal_get_path('module', 'opendata') . '/opendata.css');
  }
}

/**
 * Implements hook_help().
 */
function opendata_help($path, $arg) {
  switch ($path) {
    case 'admin/help#opendata':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("A helpful entry about your module") . '<p>';
      return $output;
  }
}
