<?php
/**
 * @file
 * Code for the Project Open Data Content feature.
 */

include_once 'opendata_content.features.inc';

/**
 * Implements hook_validate().
 *
 * 
 */
function opendata_content_node_validate($node, $form, &$form_state) {
  if ($node->type == 'opendata_dataset') {

  }
}

/**
 * Implements hook_node_submit().
 *
 * On node submit, if the node being submitted is the node created by default
 * when the opendata_content module is installed, unset the requirment error
 * indicator.
 */
function opendata_content_node_submit($node, $form, &$form_state) {
  if ($note->type == 'opendata_dataset') {
    if (!variable_get('opendata_catalog_node_updated', FALSE)) {
      $catalog_nid = variable_get('opendata_catalog_node', 0);
      if ($node->nid == $catalog_nid) {
        //they're updating the catalog node, so unset the warning
        variable_set('opendata_catalog_node_updated', TRUE);
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function opendata_content_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'opendata_dataset_node_form' ) {
    if (empty($form['field_opendata_identifier'][LANGUAGE_NONE][0]['value']['#default_value'])) {
      // Code blatantly stolen from Com::generate.
      $form['field_opendata_identifier']['und'][0]['value']['#default_value'] = opendata_content_uuid();
    }
  }
dsm($form['#validate']);
}

/**
 * Generates a unique ID.
 *
 * @return strip
 *   A unique string.
 */
function opendata_content_uuid() {
  return strtolower(sprintf('%04X%04X-%04X-%04X-%04X-%04X%04X%04X', mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(16384, 20479), mt_rand(32768, 49151), mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(0, 65535)));
}
